In [21]:
import pandas as pd
import numpy as np
import os

In [22]:
retval=os.chdir("..")

In [23]:
assignee=pd.read_csv('input/USPTO/assignee.csv')
patent_assignee = pd.read_csv('input/USPTO/patent_assignee.tsv')
kcmo = pd.read_csv('input/KCMO/business_license_2015_2017.csv')

In [4]:
kcmo = kcmo.drop_duplicates()
kcmo.describe(include = 'all')

,Business Name,DBA Name,Address,Business Type,Valid License For
count,31708,9497,31708,31708,31708
unique,29586,8850,27518,617,4
top,REDBOX AUTOMATED RETAIL LLC,CASH AMERICA PAWN OF KANSAS CITY,2405 GRAND BLVD STE 1020 KANSAS CITY MO 64108-...,Limousine Service,12/31/17
freq,65,14,37,6830,23773

In [44]:
patent_assignee

        patent_id                       assignee_id
0         8568657  3373b8ea571fe1848352b3325c8424dc
1         8366311  3373b8ea571fe1848352b3325c8424dc
2         RE43418  3373b8ea571fe1848352b3325c8424dc
3         8425775  c2b8b4ebf5c3f38a0ba747f0f4bac07b
4         7412333  c2b8b4ebf5c3f38a0ba747f0f4bac07b
5         6120431  c2b8b4ebf5c3f38a0ba747f0f4bac07b
6         4791911  c2b8b4ebf5c3f38a0ba747f0f4bac07b
7         6042567  c2b8b4ebf5c3f38a0ba747f0f4bac07b
8         7834625  c2b8b4ebf5c3f38a0ba747f0f4bac07b
9         6786902  c2b8b4ebf5c3f38a0ba747f0f4bac07b
10        9162910  c2b8b4ebf5c3f38a0ba747f0f4bac07b
11        6808482  c2b8b4ebf5c3f38a0ba747f0f4bac07b
12        7541808  c2b8b4ebf5c3f38a0ba747f0f4bac07b
13        6398715  c2b8b4ebf5c3f38a0ba747f0f4bac07b
14        6162167  c2b8b4ebf5c3f38a0ba747f0f4bac07b
15        8448848  c2b8b4ebf5c3f38a0ba747f0f4bac07b
16        6045496  c2b8b4ebf5c3f38a0ba747f0f4bac07b
17        6039730  c2b8b4ebf5c3f38a0ba747f0f4bac07b
18        7881510  c2b8b4ebf5c3f38a0ba747f0f4bac07b
19        8529961  c2b8b4ebf5c3f38a0ba747f0f4bac07b
20        8529960  c2b8b4ebf5c3f38a0ba747f0f4bac07b
21        7115732  c2b8b4ebf5c3f38a0ba747f0f4bac07b
22        8911789  c2b8b4ebf5c3f38a0ba747f0f4bac07b
23        9611491  c2b8b4ebf5c3f38a0ba747f0f4bac07b
24        8480902  c2b8b4ebf5c3f38a0ba747f0f4bac07b
25        9709564  c2b8b4ebf5c3f38a0ba747f0f4bac07b
26        8529959  c2b8b4ebf5c3f38a0ba747f0f4bac07b
27        4673639  c2b8b4ebf5c3f38a0ba747f0f4bac07b
28        8335558  c2b8b4ebf5c3f38a0ba747f0f4bac07b
29        7871791  c2b8b4ebf5c3f38a0ba747f0f4bac07b
...           ...                               ...
5629528   5359861  78a3640c0689cf36b4202b076e90934b
5629529   5494410  78a3640c0689cf36b4202b076e90934b
5629530   5482541  78a3640c0689cf36b4202b076e90934b
5629531   5415012  78a3640c0689cf36b4202b076e90934b
5629532   5585145  78a3640c0689cf36b4202b076e90934b
5629533   9217621  c401321292c8cb7fdffd8fad3aee92d2
5629534   5784108  0ad75e6e0fdd34a62f30fe35ce8603ef
5629535   5258837  0f9cbb6e9acafd378c7f72361b96fe22
5629536   D298303  1f4c3d8b4203ef0ed19315fb0b46d97b
5629537   9637895  713e93a61c5ba0f70685207b57663f09
5629538   9714503  713e93a61c5ba0f70685207b57663f09
5629539   9040023  58ff9ebf7c9bc4a79693345a40183cfd
5629540   7508764  97817a9f9990ab87b07d0abd5a5d6dd3
5629541   7606147  97817a9f9990ab87b07d0abd5a5d6dd3
5629542   7761485  97817a9f9990ab87b07d0abd5a5d6dd3
5629543   7733891  97817a9f9990ab87b07d0abd5a5d6dd3
5629544   7773510  97817a9f9990ab87b07d0abd5a5d6dd3
5629545   7719995  97817a9f9990ab87b07d0abd5a5d6dd3
5629546   7620526  97817a9f9990ab87b07d0abd5a5d6dd3
5629547   7719966  97817a9f9990ab87b07d0abd5a5d6dd3
5629548   7706291  97817a9f9990ab87b07d0abd5a5d6dd3
5629549   D764637  eceb55c52deb1c89ec9670721ae47720
5629550   9518369  eceb55c52deb1c89ec9670721ae47720
5629551   5851305  7a8b42fda710d4645f127400618541ed
5629552   9407828  7a8b42fda710d4645f127400618541ed
5629553   8797434  7a8b42fda710d4645f127400618541ed
5629554   D537549  4b044a6cdb470fe6097668e2c39b239a
5629555   D609690  880bd0ca9cd8627b948d37224d55c2a5
5629556   9650192  7ee062702c23bd9dbd906e3f2fb0127f
5629557   D555483  17dde2043396834decce02a3700e2a52

[5629558 rows x 2 columns]

In [37]:
assignee = assignee[assignee['organization'].notnull()].copy()
del assignee['type']
del assignee['name_first']
del assignee['name_last']

In [6]:
assignee['organization_clean'] = assignee['organization'].str.upper()
kcmo['business_name_clean'] = kcmo['Business Name'].str.upper()

# remove .
assignee['organization_clean'] = assignee['organization_clean'].str.replace('\.', '')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace('\.', '')


# remove .
assignee['organization_clean'] = assignee['organization_clean'].str.replace('\,', '')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace('\,', '')


# replace ' by \s
assignee['organization_clean'] = assignee['organization_clean'].str.replace('\'', ' ')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace('\'', ' ')

# replace - by \s
assignee['organization_clean'] = assignee['organization_clean'].str.replace('-', ' ')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace('-', ' ')

# Replace & by \s&\s
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'\s?&\s?', ' & ')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'\s?&\s?', ' & ')

# replace Company by CO
assignee['organization_clean'] = assignee['organization_clean'].str.replace('COMPANY', 'CO')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace('COMPANY', 'CO')

# replace National Association by NA
assignee['organization_clean'] = assignee['organization_clean'].str.replace('NATIONAL ASSOCIATION', 'NA')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace('NATIONAL ASSOCIATION', 'NA')

# replace N A by NA
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'\bN\sA\b', 'NA')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'\bN\sA\b', 'NA')

# replace U S A by USA
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'\bU\sS\sA\b', 'USA')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'\bU\sS\sA\b', 'USA')

# replace U S by US
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'\bU\sS\b', 'US')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'\bU\sS\b', 'US')


# When THE is last word, move to front
# TEMP: Remove all THE
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'^THE\b', '')
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'\bTHE$', '')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'^THE\b', '')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'\bTHE$', '')

#More radical: remove all special characters:
assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'[^A-Z\s0-9\&]', '')
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'[^A-Z\s0-9\&]', '')

#Most radical: remove all non-alpha characters
#assignee['organization_clean'] = assignee['organization_clean'].str.replace(r'[^A-Z]', '')
#kcmo['business_name_clean'] = kcmo['business_name_clean'].str.replace(r'[^A-Z]', '')

# Clean
assignee['organization_clean'] = assignee['organization_clean'].str.strip()
kcmo['business_name_clean'] = kcmo['business_name_clean'].str.strip()

In [7]:
#string = "THE"
#kcmo[kcmo['Business Name'].str.contains(string)]
#assignee[assignee['organization'].str.contains(string)]

In [8]:
kcmo_assignees = pd.merge(kcmo, assignee, how = 'left'
                          , left_on = 'business_name_clean'
                          , right_on = 'organization_clean')

In [9]:
kcmo_assignees.describe(include = 'all')

,Business Name,DBA Name,Address,Business Type,Valid License For,business_name_clean,id,organization,organization_clean
count,31737,9515,31737,31737,31737,31737,795,795,795
unique,29586,8850,27518,617,4,29581,538,538,526
top,REDBOX AUTOMATED RETAIL LLC,BANK OF AMERICA,2405 GRAND BLVD STE 1020 KANSAS CITY MO 64108-...,Limousine Service,12/31/17,REDBOX AUTOMATED RETAIL LLC,a4db0e572e9588bc686e4410c82488ac,"REDBOX AUTOMATED RETAIL, LLC",REDBOX AUTOMATED RETAIL LLC
freq,65,28,37,6830,23801,65,65,65,65

In [10]:
kcmo_patents = pd.merge(kcmo_assignees, patent_assignee, how = 'left'
                        , left_on = 'id', right_on = 'assignee_id'
                       )
del(kcmo_patents['assignee_id'])

In [11]:
kcmo_patents.describe(include = 'all')

,Business Name,DBA Name,Address,Business Type,Valid License For,business_name_clean,id,organization,organization_clean,patent_id
count,323204,30675,323204,323204,323204,323204,292262,292262,292262,292262
unique,29586,8850,27518,617,4,29581,538,538,526,215301
top,XEROX CORPORATION,NCR,PO BOX 151127 DALLAS TX 75315-1127,Consumer Electronics Repair and Maintenance,12/31/17,XEROX CORPORATION,e572ad43a89039b0d72acc4ce970a33f,Xerox Corporation,XEROX CORPORATION,9286617
freq,44474,3769,44474,69282,305946,44474,44474,44474,44474,65

In [12]:
kcmo_vars = list(kcmo)
for var in kcmo_vars:
    kcmo_patents[var] = kcmo_patents[var].fillna('')
kcmo_patents['patent_flag'] = kcmo_patents['patent_id'].notnull()
kcmo_patents_grouped = pd.DataFrame({'number_of_patents' : kcmo_patents.groupby(kcmo_vars)
                                     ['patent_flag'].agg('sum')}
                                   ).reset_index()

In [13]:
kcmo_patents_grouped.describe(include='all')

,Business Name,DBA Name,Address,Business Type,Valid License For,business_name_clean,number_of_patents
count,31708,31708,31708,31708,31708,31708,31708.000000
unique,29586,8851,27518,617,4,29581,NaN
top,REDBOX AUTOMATED RETAIL LLC,,2405 GRAND BLVD STE 1020 KANSAS CITY MO 64108-...,Limousine Service,12/31/17,REDBOX AUTOMATED RETAIL LLC,NaN
freq,65,22211,37,6830,23773,65,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,9.217295
std,NaN,NaN,NaN,NaN,NaN,NaN,387.243976
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,41692.000000

In [14]:
pd.crosstab(index = kcmo_patents_grouped['number_of_patents'], columns='count')

col_0              count
number_of_patents
0.0                30942
1.0                  144
2.0                   61
3.0                   33
4.0                   23
5.0                   46
6.0                   18
7.0                   14
8.0                   14
9.0                   23
10.0                  10
11.0                   2
12.0                  10
13.0                   7
14.0                   4
15.0                  12
16.0                  11
17.0                   1
18.0                   5
19.0                   5
20.0                  17
21.0                   3
22.0                   3
23.0                   1
24.0                   4
25.0                   6
27.0                   1
28.0                   3
29.0                   2
30.0                   6
...                  ...
978.0                  1
1037.0                 1
1089.0                 1
1111.0                 2
1122.0                 1
1154.0                 1
1199.0                 1
1266.0                 1
1414.0                 2
1470.0                 1
1499.0                 1
1604.0                13
1760.0                 1
1853.0                 1
1879.0                 1
1917.0                 1
2316.0                 1
2822.0                 1
2877.0                 1
2955.0                 1
2986.0                 1
3769.0                 1
5901.0                 1
6120.0                 3
10349.0                2
14056.0                1
21414.0                1
22237.0                2
29694.0                1
41692.0                1

[149 rows x 1 columns]

In [45]:
kcmo_patents_grouped[kcmo_patents_grouped['number_of_patents']>25000]

,Business Name,DBA Name,Address,Business Type,Valid License For,business_name_clean,number_of_patents
10927,GENERAL ELECTRIC COMPANY,,PO BOX 60320 FORT MYERS FL 33906-6320,Consumer Electronics Repair and Maintenance,12/31/17,GENERAL ELECTRIC CO,41692.0
19475,MICROSOFT CORPORATION,,1 MICROSOFT WAY REDMOND WA 98052-8300,All Other Business Support Services,12/31/17,MICROSOFT CORPORATION,29694.0

In [16]:
pd.crosstab(index = kcmo_patents_grouped['number_of_patents'], columns='count', normalize=True)

col_0                 count
number_of_patents
0.0                0.975842
1.0                0.004541
2.0                0.001924
3.0                0.001041
4.0                0.000725
5.0                0.001451
6.0                0.000568
7.0                0.000442
8.0                0.000442
9.0                0.000725
10.0               0.000315
11.0               0.000063
12.0               0.000315
13.0               0.000221
14.0               0.000126
15.0               0.000378
16.0               0.000347
17.0               0.000032
18.0               0.000158
19.0               0.000158
20.0               0.000536
21.0               0.000095
22.0               0.000095
23.0               0.000032
24.0               0.000126
25.0               0.000189
27.0               0.000032
28.0               0.000095
29.0               0.000063
30.0               0.000189
...                     ...
978.0              0.000032
1037.0             0.000032
1089.0             0.000032
1111.0             0.000063
1122.0             0.000032
1154.0             0.000032
1199.0             0.000032
1266.0             0.000032
1414.0             0.000063
1470.0             0.000032
1499.0             0.000032
1604.0             0.000410
1760.0             0.000032
1853.0             0.000032
1879.0             0.000032
1917.0             0.000032
2316.0             0.000032
2822.0             0.000032
2877.0             0.000032
2955.0             0.000032
2986.0             0.000032
3769.0             0.000032
5901.0             0.000032
6120.0             0.000095
10349.0            0.000063
14056.0            0.000032
21414.0            0.000032
22237.0            0.000063
29694.0            0.000032
41692.0            0.000032

[149 rows x 1 columns]

In [ ]:
#########################
#########################
#########################

In [33]:
# Check Edward Jones

In [28]:
kcmo[(kcmo['Business Name'].str.contains("EDWARD"))
     &(kcmo['Business Name'].str.contains("JONES"))
    ]

,Business Name,DBA Name,Address,Business Type,Valid License For
965,EDWARD D JONES & CO ET AL,NaN,6751 N PENNSYLVANIA AVE KANSAS CITY MO 64118-3274,Miscellaneous Intermediation,12/31/17
2084,EDWARD D JONES & CO ET AL,NaN,508 W 75TH ST STE A KANSAS CITY MO 64114-1500,Miscellaneous Intermediation,12/31/17
4915,EDWARD D JONES & CO ET AL,NaN,8560 N GREEN HILLS RD STE 124 KANSAS CITY MO 6...,Miscellaneous Intermediation,12/31/17
5188,EDWARD D JONES & CO ET AL,NaN,PO BOX 66719 SAINT LOUIS MO 63166-6719,Miscellaneous Intermediation,12/31/17
7655,EDWARD D JONES & CO ET AL,EDWARD D JONES & CO,11131 LOCUST ST KANSAS CITY MO 64131-3622,Miscellaneous Intermediation,12/31/17
7765,EDWARD D JONES & CO ET AL,NaN,29 NW BARRY RD KANSAS CITY MO 64155-2728,Miscellaneous Intermediation,12/31/17
11866,EDWARD D JONES & CO ET AL,NaN,4149 PENNSYLVANIA AVE STE 102 KANSAS CITY MO 6...,Miscellaneous Intermediation,12/31/17
12407,EDWARD D JONES & CO ET AL,NaN,4151 N MULBERRY DR STE 206 KANSAS CITY MO 6411...,Miscellaneous Intermediation,12/31/17
13884,EDWARD D JONES & CO ET AL,NaN,7705 NW PRAIRIE VIEW RD KANSAS CITY MO 64151-1542,Miscellaneous Intermediation,12/31/17
15450,EDWARD D JONES & CO ET AL,NaN,9237 WARD PKWY STE 101 KANSAS CITY MO 64114-3357,Miscellaneous Intermediation,12/31/17
17493,EDWARD D JONES & CO ET AL,NaN,4401 NE VIVION RD KANSAS CITY MO 64119-2810,Miscellaneous Intermediation,12/31/17
19986,EDWARD D JONES & CO ET AL,NaN,4266 N OAK TRFY KANSAS CITY MO 64116-4541,Miscellaneous Intermediation,12/31/17
20489,EDWARD D JONES & CO ET AL,NaN,8532 N AMBASSADOR DR KANSAS CITY MO 64154-2559,Miscellaneous Intermediation,12/31/17
21797,EDWARD D JONES & CO ET AL,NaN,601 E 63RD ST STE 420 KANSAS CITY MO 64110-3303,Miscellaneous Intermediation,12/31/17
22094,EDWARD D JONES & CO ET AL,NaN,8012 N BRIGHTON AVE KANSAS CITY MO 64119-1411,Miscellaneous Intermediation,12/31/17
23893,EDWARD D JONES & CO ET AL,NaN,4900 MAIN ST STE 320 KANSAS CITY MO 64112-2683,All Other Professional Scientific and Technica...,12/31/17
24210,EDWARD D JONES & CO ET AL,NaN,9243 N OAK TRFY KANSAS CITY MO 64155-3392,Miscellaneous Intermediation,12/31/17
26598,EDWARD D JONES & CO ET AL,NaN,6241 BROOKSIDE PLZ KANSAS CITY MO 64113-1607,Miscellaneous Intermediation,12/31/17

In [32]:
assignee[(assignee['organization'].str.contains("Edward"))
         &(assignee['organization'].str.contains("Jones"))
        ]

,id,type,name_first,name_last,organization
61909,29ffc08ca93cd5db078e3631006736b8,0,NaN,NaN,Edward Jones & Co.
154995,694c4354f5956127301db7872c7ae4e0,0,NaN,NaN,Edwards & Jones Limited
278693,bd6c3ad863099e0d603ef5d2fd9072e9,0,NaN,NaN,"Edward D. Jones & Co., L.P."

In [34]:
# Drop Eastern Enterprises? Example of H&R
# CASH AMERICA OF MISSOURI INC vs. CASH AMERICA INTERNATIONAL, INC.
# ALDI INC KANSAS vs ALDI EINKAUF GMBH & CO. OHG
# BRIDGESTONE RETAIL
# PRICE BROTHERS MANAGEMENT COMPANY vs. PRICE BROTHERS COMPANY
#

In [36]:
kcmo[(kcmo['Business Name'].str.contains("H&R"))
#     &(kcmo['Business Name'].str.contains("EN"))
    ]

,Business Name,DBA Name,Address,Business Type,Valid License For
4219,H&R BLOCK HEALTH INSURANCE AGENCY INC,NaN,ONE H&R BLOCK WAY KANSAS CITY MO 64105-0000,Insurance Agencies and Brokerages,12/31/17
5453,H&R BLOCK GROUP INC,NaN,PO BOX 32208 KANSAS CITY MO 64171-5208,All Other Professional Scientific and Technica...,12/31/17
17264,H&R BLOCK TAX INSTITUTE LLC,NaN,1 H AND R BLOCK WAY KANSAS CITY MO 64105-1905,All Other Professional Scientific and Technica...,12/31/17
18785,H&R BLOCK PREMIUM,NaN,1 H AND R BLOCK WAY KANSAS CITY MO 64105-1905,Other Accounting Services,12/31/17
18988,H&R BLOCK CLIENT RESEARCH & SUPPORT SERVICES LLC,NaN,PO BOX 32208 KANSAS CITY MO 64171-5208,All Other Business Support Services,12/31/17
19438,H&R BLOCK TAX RESOLUTION SERVICES INC,NaN,1 H AND R BLOCK WAY FL 9 KANSAS CITY MO 64105-...,All Other Professional Scientific and Technica...,12/31/17

In [35]:
assignee[(assignee['organization'].str.contains("H&R"))
#         &(assignee['organization'].str.contains("Jones"))
        ]

ValueError: cannot index with vector containing NA / NaN values

In [53]:
test = pd.crosstab(index = kcmo['Business Name'], columns = 'count')

In [120]:
test[(test['count']<11)&(test['count']>7)]

col_0                                count
Business Name
ADVANCE STORES COMPANY INCORPORATED      8
ALDI INC KANSAS                          8
AMERICAN TOWER DELAWARE CORPORATION     10
BRIDGESTONE RETAIL OPERATIONS LLC        8
ECOATM LLC                              10
HY VEE INC                               8
MATTRESS FIRM INC                        9
MILLENNIUM OPERATIONS LLC               10
MJV-A LLC                                9
O G INVESTMENTS                          8
O REILLY AUTOMOTIVE STORES INC          10
PRICE BROTHERS MANAGEMENT COMPANY        8
QC FINANCIAL SERVICES INC                8
SHERWIN WILLIAMS CO THE                  9
STARBUCKS CORPORATION                    9
U S BANK NATIONAL ASSOCIATION            9

In [51]:
kcmo.shape

(31778, 5)

In [52]:
kcmo_assignees.shape

(31778, 10)

In [19]:
#assignee2 = assignee.copy()
#assignee2['organization'] = assignee2['organization'].fillna('')
assignee[(assignee['organization_clean'].str.contains('XEROX'))
#          &(assignee2['organization'].str.contains('WILLIAMS'))
         ]

,id,organization,organization_clean
23682,10356ea1aa03950172180be5645b4df4,Xerox Company,XEROX CO
47917,209919bdcc9d9eeb3da2102d2105aff7,"Suzuka Fuji Xerox Co., Ltd.",SUZUKA FUJI XEROX CO LTD
79773,363b9527798eb9d0e31da2ee8631da76,Xerox PARC,XEROX PARC
90158,3d59d1a0c786b2ca544df3c6328a05be,"Fuji Xerox Engineering Co., Ltd.",FUJI XEROX ENGINEERING CO LTD
119287,5131f51788d40288898fac70c863b75b,Xerox International Partners,XEROX INTERNATIONAL PARTNERS
127074,5681e2ad4599f86f00d51fb8dfabf212,"Xerox Business Services, LLC",XEROX BUSINESS SERVICES LLC
129241,57ef9a1f208eab1a9c7352b6946b395c,"Fuji Xerox Office Supply Co., Ltd.",FUJI XEROX OFFICE SUPPLY CO LTD
145939,6345d60dd32adc907e75cb4bf345ec5d,Xerox Corp.,XEROX CORP
150781,667c95f71f2f3d5b5c4dadd7d6b13eb9,Rank Xerox Ltd.,RANK XEROX LTD
151581,66fd467f2b517825791ca0314adfed56,"Fuji Xerox Co., Ltd.",FUJI XEROX CO LTD
161415,6d964c8ceac2f0c5fb0401794e0a2936,"Fuji Xerox Corporation, Ltd.",FUJI XEROX CORPORATION LTD
196954,85d3a2a25685b4a49a6ea1f00a455edc,Kuji Xerox Co. Ltd.,KUJI XEROX CO LTD
197086,85eb8d372baf78beb4f31daf55ad429a,"Stamford, Xerox Corporation",STAMFORD XEROX CORPORATION
201918,8932e32ecb9b9d8df2541386658dff77,Fuji-Xerox Company Ltd.,FUJI XEROX CO LTD
248158,a890527c4c9ccdc79f61bd7a78898a75,Fuji Xerox,FUJI XEROX
273762,ba109074f888372b7af8902c8c166621,Rank Xerox SA,RANK XEROX SA
295329,c8c243790ff904fec21bea63f3de3366,Xerox Corporation Stamford,XEROX CORPORATION STAMFORD
297870,ca7e686dd54f61172df5bb1bbaeb5ed0,"Xerox State & Local Solutions, Inc.",XEROX STATE & LOCAL SOLUTIONS INC
310638,d32541ad875d22143d2301d62540bfb3,"Xerox Canada, Inc.",XEROX CANADA INC
337796,e572ad43a89039b0d72acc4ce970a33f,Xerox Corporation,XEROX CORPORATION
344978,ea30ac4e7fab386732f700380ce39137,Xerox,XEROX
369498,fae1d8e84a4788149e3f359cfff742c9,"Fuji Xerox Co., Inc.",FUJI XEROX CO INC

In [232]:
count = pd.crosstab(index = assignee['organization_clean'], columns = 'count')

In [235]:
assignee[assignee['organization_clean']=='ZOELLER CO']

,id,type,name_first,name_last,organization,organization_clean
210710,8f3d80d7df28c57536479a45d887a49e,0,NaN,NaN,ZOELLER COMPANY,ZOELLER CO
334204,e30119ab4f472a3d30f4caa149bd7e52,0,NaN,NaN,ZOELLER CO.,ZOELLER CO

In [18]:
assignee

,id,organization,organization_clean
0,00003f5c5d92354570b9bae01b3e7272,"E-Z Anchor Bolt Template, Inc.",E Z ANCHOR BOLT TEMPLATE INC
1,000058159cdbf11415ffad8001c192f6,Roll and Go AG,ROLL AND GO AG
2,00005a7b722c0d70af7c0f6706cdc067,PERSCITUS INNOVATIONS LLC,PERSCITUS INNOVATIONS LLC
3,00007b72e8f46f63797266c63ad3a34f,"Fleetwood Aluminum Products, Inc.",FLEETWOOD ALUMINUM PRODUCTS INC
4,000099cec50350524fc0704f0cdd8db6,B.V. Nederlandse Industrie Van Eiprodukten,BV NEDERLANDSE INDUSTRIE VAN EIPRODUKTEN
5,00010ed73d92d44448d6a95ea2bdfc82,Kirkplastic Company Incorporated,KIRKPLASTIC CO INCORPORATED
6,00012f928641d531b8cd4604135b4426,LIVSMED INC.,LIVSMED INC
8,0001fec1a13a81b11892a8a1b7e9e26a,"Terrybear, Inc.",TERRYBEAR INC
9,000297b2fe80676ac2443715ece07065,Evince Technology Limited,EVINCE TECHNOLOGY LIMITED
10,0002ca8fa44fafd53223a9c280f0a302,Shanghai A&S Science Technology Development Co...,SHANGHAI A & S SCIENCE TECHNOLOGY DEVELOPMENT ...
11,0002cb9ed9c80bb4d5118517da40d6b7,Supreme Premium Products Inc.,SUPREME PREMIUM PRODUCTS INC
12,0002f31315a48b02cf1911e0f4274965,Coretek Opto Corporation,CORETEK OPTO CORPORATION
13,00032dc66f4fbe33d98542427fbf286a,Almo Manifold & Tool Company,ALMO MANIFOLD & TOOL CO
14,0003307889ecfc5d06d4035795628ed2,"D. Gioielli, Inc.",D GIOIELLI INC
15,0003a4cb6aa22e585478331b1937529d,"Western Reserve Electronics, Inc.",WESTERN RESERVE ELECTRONICS INC
16,0003f46cdb3278b996c83205095deeb0,Mats Thulin AB,MATS THULIN AB
17,00045b45518d59431ec0a6bd48bc1df3,Mayo Foundation,MAYO FOUNDATION
18,00045e7585e9e231e1fa572845775569,Megomat AG,MEGOMAT AG
19,0004d228d44fd0816cba5cdebedf8fa4,"Tokan Material Technology Co., Ltd.",TOKAN MATERIAL TECHNOLOGY CO LTD
20,0004eb61fbc3fb2dfb2c72a8d458751c,"Advantage Industries, Inc.",ADVANTAGE INDUSTRIES INC
21,000513c5c6deb9da259c8d831adf4297,Lawson Automotive Inc.,LAWSON AUTOMOTIVE INC
22,00052ca72a0568cf8a0e7bef1f069510,"MadGrip Holdings, LLC",MADGRIP HOLDINGS LLC
23,000536f0ae96cbeaf0fa2bd882efe2cd,Arrow Line S.r.l.,ARROW LINE SRL
25,00058979304632a95c9b697e4705aacd,"Young Microbrush, LLC",YOUNG MICROBRUSH LLC
26,0005a2307b9f4eaaabc44c8cec1c8f1f,"Dragon Heart Medical Devices Co., Ltd.",DRAGON HEART MEDICAL DEVICES CO LTD
27,0005a9078efc46e2183cc01a07541e85,Multi-Metal Wire Cloth Inc.,MULTI METAL WIRE CLOTH INC
28,0005ad9738860051dad6509e1a418fb7,Logitech Incorporated,LOGITECH INCORPORATED
29,0005c3e6a482c01654865c0ba9ba24fc,"INTERNATIONAL FRUIT GENETICS, LLC",INTERNATIONAL FRUIT GENETICS LLC
30,0005eb340ec633d8189c5f4cd64a82a7,"POINT TEK CO., LTD.",POINT TEK CO LTD
31,00062227de055ff58a3ba573d8e6a8f1,Societe Anonyme d'Etudes et Realisations Nucle...,SOCIETE ANONYME D ETUDES ET REALISATIONS NUCLE...
...,...,...,...
376879,fffbe58389a8129564d6e26c82ad992d,Walsh Intellectual Property Ltd.,WALSH INTELLECTUAL PROPERTY LTD
376881,fffc043d8b798ac2b1826be7d7fb00ae,Videotec S.R.L.,VIDEOTEC SRL
376883,fffc1d7fcf26bad8b722014c3b81e611,"Marketing Concepts, Inc.",MARKETING CONCEPTS INC
376884,fffc39aaba9ce144f789e3726ea6ed39,CROSSFORD ENTERPRISES PY LTD,CROSSFORD ENTERPRISES PY LTD
376885,fffc3ce948491a3f31c175f2db9c9390,"Spectra Pharmaceutical Services, Inc.",SPECTRA PHARMACEUTICAL SERVICES INC
376886,fffcd72d7d09095a65ef444d39976458,Stark Brothers Nurseries and Orchards Co.,STARK BROTHERS NURSERIES AND ORCHARDS CO
376887,fffd24cb01724d988385834219c4c5bd,"Velo Mobile Health, Inc.",VELO MOBILE HEALTH INC
376888,fffd348e3bcd2a7ae19206dc5fa92f4f,AMCO Partnership,AMCO PARTNERSHIP
376889,fffd3a9be10a47188f0cd3086b94770b,AB Svenska Eketromagneter,AB SVENSKA EKETROMAGNETER
376890,fffd536d3b39a71639dd5ed4436bae2b,Fa. Lumoprint Zindler KG (GmbH & Co.),FA LUMOPRINT ZINDLER KG GMBH & CO
376891,fffd6de0edb390666d0bedfebe8268b6,OT IMPLANT S.R.L.,OT IMPLANT SRL
376892,fffdaab587f87800009b9d6a4ae0145f,"Applied Polymer Technology, Inc.",APPLIED POLYMER TECHNOLOGY INC
376893,fffdaf89b9f885650cfe855d385b662c,"Plantenwekerij J. Van Geest, B.V.",PLANTENWEKERIJ J VAN GEEST BV
376895,fffdce3693fe82052d12baea398cf0aa,Klockner-Humboldt-Deutz Aktiengesellschaft,KLOCKNER HUMBOLDT DEUTZ AKTIENGESELLSCHAFT
376896,fffe15cd6896a437468793b5e7f2d02e,"Aurora Lighting, Inc.",AURORA LIGHTING INC
376897,fffe2da537893f5ec2ee7383ca47b0ca,Milli-Henry Enterprise Co.,MILLI HENRY ENTERPRISE CO
376898,fffe30e4678e7f12bd60f4334bf9a9ca,"G&R Equipment, LLC",G & R EQUIPMENT LLC
376900,fffe577d20375c1cd0e3e08016cafdac,ADVENTIVE IPBANK,ADVENTIVE IPBANK
376901,fffe7624fffacbeba1452d91ddd9ee1b,"Morita Fire Pump Mfg. Co., Ltd.",MORITA FIRE PUMP MFG CO LTD
376902,fffeb51517719356940616c840d7e1ba,"Little Luxuries, Ltd.",LITTLE LUXURIES LTD
376903,fffebb9490c34e679d2e1764509d5fba,Wintershall AG,WINTERSHALL AG
376904,ffff0b2efa1db3e754c5bd79f11ad52e,"Interfax, Inc.",INTERFAX INC
376905,ffff0f2f08f2bd3cdfe5901c37c84a1c,E. Rapp Electronik GmbH,E RAPP ELECTRONIK GMBH
376906,ffff6cc9f9d8f349288fba6da2b4073d,HF Holding S.A.,HF HOLDING SA
376907,ffff9c90108203a0bb04e36e8cb5fe87,"Nippon Rotary Nozzle Co., Ltd.",NIPPON ROTARY NOZZLE CO LTD
376908,ffffa03623889f1daa89e1ba4bb84f60,"IntelliWheels, Inc.",INTELLIWHEELS INC
376909,ffffa8adcfecf1d9c926de6685694922,Ingenuity Express Corp.,INGENUITY EXPRESS CORP
376910,ffffc0caab5c1595933b0a90df9d4cb7,"D.C. Henning, Inc.",DC HENNING INC
376911,ffffc5eaa8d3d7c8872a91ed0f47de48,"TechSys, LLC",TECHSYS LLC
376912,ffffedb67ee6a8e3d8d9985c2f8f9758,Argus Verwaltungsgesellschaft mbH,ARGUS VERWALTUNGSGESELLSCHAFT MBH

In [46]:
kcmo

,Business Name,DBA Name,Address,Business Type,Valid License For
0,ANDREA CRAIG,NaN,519 N KANSAS AVE OLATHE KS 66061-2646,Limousine Service,12/31/17
1,OWDA LLC,CLUB TANQUERAY,5510 E TRUMAN RD KANSAS CITY MO 64127-2436,Drinking Places (Alcoholic Beverages),12/31/17
2,DALEREA CORPORATION,NaN,2029 GRAND BLVD KANSAS CITY MO 64108-1883,Administrative Management and General Manageme...,12/31/17
3,SERVICE EXPERTS HEATING & AIR CONDITIONING LLC,NaN,9040 CODY ST OVERLAND PARK KS 66214-1730,Commercial and Institutional Building Construc...,12/31/17
4,LANDES TYLER J,NaN,7534 OAK ST KANSAS CITY MO 64114-1945,Other Accounting Services,12/31/17
5,MARTIN RENEE H,NaN,12118 E 54TH TER KANSAS CITY MO 64133-3073,Limousine Service,12/31/16
6,EVANS BENJAMIN L,NaN,3249 E 28TH ST KANSAS CITY MO 64128-1202,Mobile Food Services,12/31/17
7,JOHN GRAHAM,NaN,7912 CORONA AVE KANSAS CITY KS 66112-2126,Limousine Service,12/31/17
8,R & M COMMUNICATIONS LLC,NaN,4601 PROSPECT AVE KANSAS CITY MO 64130-1958,Electrical Contractors and Other Wiring Instal...,12/31/16
9,BERNITSKY LAURA,NaN,2901 OAK ST APT 204 KANSAS CITY MO 64108-3379,Limousine Service,12/31/17
10,FRESH CATERING KC LLC,NaN,30265 PO BOX KANSAS CITY MO 64112-3265,Caterers,12/31/15
11,GARRET WHITEMAN,NaN,601 SE STEEPLE CT BLUE SPRINGS MO 64014-3848,Limousine Service,12/31/17
12,U S FENCE COMPANY OF KC,NaN,15304 LOWELL AVE OVERLAND PARK KS 66223-2765,Commercial and Institutional Building Construc...,12/31/17
13,MERRITT KIMBERLEY,K & C SERVICE,8525 E 59TH ST KANSAS CITY MO 64129-2762,Janitorial Services,12/31/17
14,RS SERVICES INC,NaN,5424 W 100TH ST OVERLAND PARK KS 66207-3116,Commercial and Institutional Building Construc...,12/31/17
15,MAX RIEKE & BROS INC,MAX RIEKE & BROTHERS INC,15400 MIDLAND DR SHAWNEE KS 66217-9606,General Freight Trucking Long-Distance Truckload,12/31/17
16,MIDWAY U S A INC,MIDWAY USA COLLISION CENTER,3420 GARDNER AVE KANSAS CITY MO 64120-1811,Other Automotive Mechanical and Electrical Rep...,12/31/17
17,RIVER ELECTRIC LLC,NaN,549 W SHORES RD LONE JACK MO 64070-7166,Commercial and Institutional Building Construc...,12/31/17
18,TIEHEN REALTY LLC,NaN,3401 COLLEGE BLVD STE 250 LEAWOOD KS 66211-1911,Offices of Real Estate Agents and Brokers,12/31/17
19,NPIF2 THREE TRAILS BUILDING II LLC,NaN,8750 ELMWOOD AVE. KANSAS CITY MO 64132-0000,All Other Professional Scientific and Technica...,12/31/17
20,WM TIRE RECOVERY SERVICES LLC,NaN,2531 PROSPECT AVE KANSAS CITY MO 64127-3944,All Other Miscellaneous Store Retailers (excep...,12/31/16
21,BARNES JR RONNIE J,NaN,3443 AGNES AVE KANSAS CITY MO 64128-1948,Limousine Service,12/31/16
22,DONALDSON MECHANICAL INC,NaN,934 SE 7TH TER STE B LEES SUMMIT MO 64063-4800,Commercial and Institutional Building Construc...,12/31/17
23,MIDWEST CUSTOM CONTRACTORS INC,NaN,12004 E 214TH ST PECULIAR MO 64078-8309,Residential Remodelers,12/31/17
24,SANDERS MICHAEL,NaN,13817 W 54TH TER SHAWNEE KS 66216-5106,Limousine Service,12/31/17
25,ATLAS PROPERTY VENTURES LLC,NaN,4300 NE 85TH ST KANSAS CITY MO 64156-7814,Residential Remodelers,12/31/16
26,BORUSHESKI BOB A,NaN,4303 NE 58TH TER KANSAS CITY MO 64119-2895,Commercial and Institutional Building Construc...,12/31/15
27,DRAFTPROS INC.,NaN,4700 HAPPY LN ARNOLD MO 63010-3251,Power and Communication Line and Related Struc...,12/31/16
28,GOWIN PETER E,TIN ROOF PRESS,5733 MC GEE KANSAS CITY MO 64113-0000,Piece Goods Notions and Other Dry Goods Mercha...,12/31/17
29,N.E.P. NEVER ENDING PLEASURES LLC,NaN,7912 PROSPECT AVE KANSAS CITY MO 64132-2309,All Other Professional Scientific and Technica...,12/31/16
...,...,...,...,...,...
31748,ALL NATIONS FASHION STORE LLC,NaN,3624 INDEPENDENCE AVE KANSAS CITY MO 64124-2730,Family Clothing Stores,12/31/17
31749,KMD DEVELOPMENT GROUP LLC,NaN,2420 E LINWOOD BLVD STE 210 KANSAS CITY MO 641...,Lessors of Residential Buildings and Dwellings,12/31/18
31750,KNOBBE JAMES,NaN,722 WALNUT ST APT 606 KANSAS CITY MO 64106-1611,Computer Systems Design Services,12/31/16
31751,CHRISTOPH DAVIS,NaN,9 NW 83RD ST KANSAS CITY MO 64118-1137,Limousine Service,12/31/17
31752,DANIEL MERCER III,NaN,18693 W 117TH ST OLATHE KS 66061-6555,Limousine Service,12/31/17
31753,NOVOTNEY CRAIG,NaN,12439 FARROW AVE KANSAS CITY KS 66109-7101,Limousine Service,12/31/17
31754,HOTH TRACY,SIMPLY SQUARED AWAY,9900 N WAYNE AVE KANSAS CITY MO 64155-2134,All Other Business Support Services,12/31/17
31755,BULL RANDY,R & B ENTERPRISES,PO BOX 1836 LEES SUMMIT MO 64063-7836,Commercial and Institutional Building Construc...,12/31/15
31756,BRENDA EVANS,NaN,3300 CORONADO RD # 16 KANSAS CITY KS 66104-5145,Limousine Service,12/31/17
31757,ANDERSON & SONS TRUCKING INC,NaN,108 S 102ND ST EDWARDSVILLE KS 66111-1268,General Freight Trucking Long-Distance Truckload,12/31/17
31758,MICHAEL BROWN,NaN,8136 N OVERLAND DR KANSAS CITY MO 64151-1012,Limousine Service,12/31/16
31759,LANE BRYANT INC,NaN,8600 WARD PKWY STE 2100 KANSAS CITY MO 64114-2627,Family Clothing Stores,12/31/17
31760,COMBO INC,NaN,343 NW 12TH ST BLUE SPRINGS MO 64015-3644,Commercial and Institutional Building Construc...,12/31/17
31761,TAWAKAL HALAL STORE INC,NaN,3009 1/2 INDEPENDENCE AVE KANSAS CITY MO 64124...,Supermarkets and Other Grocery (except Conveni...,12/31/17
31762,TIMOTHY EMERSON,EMERSON & CO.,1001 WESTPORT RD KANSAS CITY MO 64111-4907,Payroll Services,12/31/17
31763,BRYAN REEVES,NaN,5438 HIGHLAND AVE KANSAS CITY MO 64110-2902,Commercial and Institutional Building Construc...,12/31/15
31764,RACHID ZMERDA,NaN,2625 S SHRANK RD INDEPENDENCE MO 64057-1229,Limousine Service,12/31/17
31765,TED SHOUSH CO INC,NaN,PO BOX 1081 INDEPENDENCE MO 64051-0581,Commercial and Institutional Building Construc...,12/31/17
31766,K&H COMMUNICATIONS,NaN,713 SQUIRE CT GRAIN VALLEY MO 64029-9369,All Other Professional Scientific and Technica...,12/31/16
31767,MCCORD BRANDON,SALON SKILLZ,6122 TROOST AVE KANSAS CITY MO 64110-3436,Beauty Salons,12/31/15
31768,HOLLYWOOD WHOLESALE,NaN,4131 E TRUMAN RD KANSAS CITY MO 64127-2237,All Other Miscellaneous Store Retailers (excep...,12/31/17
31769,ART MARBLE FURNITURE INC,NaN,1501 W 29TH ST KANSAS CITY MO 64108-3605,Piece Goods Notions and Other Dry Goods Mercha...,12/31/17
31770,ARASH YOUSEFIARJMAND,NaN,5628 NW 87TH TER APT C352 KANSAS CITY MO 64154...,Limousine Service,12/31/17
31771,SANDPIPER ENTERPRISES INC,NaN,5119 SW SANDPIPER DR LEES SUMMIT MO 64082-4543,Commercial and Institutional Building Construc...,12/31/15
31772,TEHRANI KAMRAN A,NaN,4118 BROADWAY # 101 KANSAS CITY MO 64111-2682,Limousine Service,12/31/17
31773,SCRATCH BAKERY KC LLC,NaN,310 W 8TH ST KANSAS CITY MO 64105-1513,Packaged Frozen Food Merchant Wholesalers,12/31/17
31774,M C S INC,OAK HILL 66,9351 N OAK TRFY KANSAS CITY MO 64155-2264,Supermarkets and Other Grocery (except Conveni...,12/31/15
31775,VISION CONSTRUCTION CO LLC,NaN,9845 ABERDEEN DR LEAWOOD KS 66206-2264,Roofing Contractors,12/31/16
31776,NAGELY ROBERT G,NaN,1310 LAKESHORE DR SABETHA KS 66534-1508,Limousine Service,12/31/17
31777,JERRY SMITH,NaN,3302 S 22ND ST SAINT JOSEPH MO 64503-3318,Limousine Service,12/31/16

In [49]:
pd.crosstab(kcmo['Business Type'], kcmo['Valid License For'])

Valid License For,12/31/15,12/31/16,12/31/17,12/31/18
Business Type,,,,
Adhesive Manufacturing,0,0,1,0
Administration of Education Programs,0,0,4,0
Administration of General Economic Programs,0,0,2,0
Administration of Housing Programs,1,0,0,0
Administration of Urban Planning and Community and Rural Development,0,0,1,0
Administrative Management and General Management Consulting Services,24,28,245,0
Advertising Agencies,5,12,61,0
Advertising Material Distribution Services,1,1,9,0
Agents and Managers for Artists Athletes Entertainers and Other Public Figures,69,17,15,0
Air Traffic Control,0,0,1,0
Air-Conditioning and Warm Air Heating Equipment and Commercial and Industrial Refrigeration Equipment Manufacturing,0,1,1,0
Aircraft Manufacturing,0,0,2,0
All Other Amusement and Recreation Industries,0,2,2,0
All Other Animal Production,2,1,10,0
All Other Automotive Repair and Maintenance,3,3,16,0
All Other Basic Organic Chemical Manufacturing,0,0,1,0
All Other Business Support Services,187,158,1062,1
All Other Consumer Goods Rental,0,0,3,0
All Other Converted Paper Product Manufacturing,0,0,1,0
All Other General Merchandise Stores,108,104,798,2
All Other Health and Personal Care Stores,2,2,15,0
All Other Home Furnishings Stores,5,7,43,0
All Other Information Services,0,0,3,0
All Other Insurance Related Activities,0,1,3,0
All Other Leather Good and Allied Product Manufacturing,0,0,2,0
All Other Legal Services,2,2,10,0
All Other Miscellaneous Ambulatory Health Care Services,1,1,4,0
All Other Miscellaneous Chemical Product and Preparation Manufacturing,0,1,7,0
All Other Miscellaneous Crop Farming,0,0,1,0
All Other Miscellaneous Electrical Equipment and Component Manufacturing,1,0,4,0
...,...,...,...,...
Transportation Equipment and Supplies (except Motor Vehicle) Merchant Wholesalers,0,0,2,0
Travel Agencies,3,0,34,0
Travel Trailer and Camper Manufacturing,0,0,2,0
Truck Utility Trailer and RV (Recreational Vehicle) Rental and Leasing,1,0,0,0
Trust Fiduciary and Custody Activities,3,2,5,0
Used Car Dealers,14,13,70,4
Used Household and Office Goods Moving,0,0,3,0
Used Merchandise Stores,5,4,18,0
Vending Machine Operators,4,4,32,0
Veterinary Services,0,0,4,0
Voluntary Health Organizations,0,0,1,0
Warehouse Clubs and Supercenters,0,0,1,0
Warm Air Heating and Air-Conditioning Equipment and Supplies Merchant Wholesalers,0,2,7,0
Water Supply and Irrigation Systems,0,0,1,0
Water and Sewer Line and Related Structures Construction,0,0,2,0
Welding and Soldering Equipment Manufacturing,1,0,0,0
Wholesale Trade Agents and Brokers,0,2,5,0
Window Treatment Stores,0,0,2,0
Wine and Distilled Alcoholic Beverage Merchant Wholesalers,0,0,4,0
Wineries,0,0,3,0
Wireless Telecommunications Carriers (except Satellite),2,0,9,0
Women's Children's and Infants' Clothing and Accessories Merchant Wholesalers,0,0,2,0
Women's Clothing Stores,3,0,14,0
Women's Handbag and Purse Manufacturing,0,0,1,0
Womenâ€™s Girlsâ€™ and Infantsâ€™ Cut and Sew Apparel Manufacturing,1,0,1,0
Wood Container and Pallet Manufacturing,1,0,0,0
Wood Kitchen Cabinet and Countertop Manufacturing,0,0,2,0
Wood Office Furniture Manufacturing,1,0,1,0
Wood Window and Door Manufacturing,0,0,1,0
Zoos and Botanical Gardens,0,0,1,0